stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            tree: true
            translatable: true
            timestampable: true
            loggable: true
            sortable: true
            softdeleteable: true
            sluggable: true