imports:
    - { resource: parameters.yml }
    # init-cms
    - { resource: cms/security_config.yml }
    - { resource: cms/sonata_admin.yml }
    - { resource: cms/sonata_doctrine_admin.yml }
    - { resource: cms/sonata_block.yml }
    - { resource: cms/stof_doctrine_extensions.yml }
    - { resource: cms/symfony_cmf_routing_extra.yml }
    - { resource: cms/mopa_bootstrap.yml }
    - { resource: cms/sonata_media.yml }
    - { resource: cms/jms_serializer.yml }
    - { resource: cms/lexik_translation.yml }
    - { resource: cms/ibrows_sonata_translation.yml }
    - { resource: cms/ivory_ck_editor.yml }

framework:
    #esi:             ~
    translator:      { fallback: 'en'}
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"


# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules/]
            apply_to: "\.less$"
        cssrewrite: ~
        cssembed:
            jar: %kernel.root_dir%/Resources/java/cssembed-0.3.6.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        mapping_types:
            enum: string


    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager:   default
        entity_managers:
            default:
                auto_mapping:     true
                connection:       default
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_sortable:
                        type: annotation
                        prefix: Gedmo\Sortable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Sortable/Entity"
                        alias: GedmoSortable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    FOSUserBundle: ~


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

networking_init_cms:
    class:
        page: "Application\\Networking\\InitCmsBundle\\Entity\\Page"
        user: "Application\\Networking\\InitCmsBundle\\Entity\\User"
    languages:
        - {label: English, locale: en_US, short_label: en}
        - {label: Deutsch, locale: de_CH, short_label: de}
        - {label: Русский, locale: ru_RU, short_label: ru}
    templates:
        'Sandbox_one_column_template':
            template: "ApplicationNetworkingInitCmsBundle:Default:one_column.html.twig"
            name: "Single Column"
            icon: "bundles/applicationnetworkinginitcms/img/template_header_one_column.png"
            zones:
                - { name: header, span:12 }
                - { name: main_content, span:12}
#                - { name: bottom, span:12}
        'Sandbox_two_column_template':
            template: "ApplicationNetworkingInitCmsBundle:Default:two_column.html.twig"
            name: "Two Column"
            icon: "bundles/applicationnetworkinginitcms/img/template_header_two_column.png"
            zones:
                - { name: header , span:12}
                - { name: left , span:6}
                - { name: right , span:6}

    content_types:
        - { name: 'Text' , class: 'Networking\InitCmsBundle\Entity\Text'}
        - { name: 'Gallery' , class: 'Networking\InitCmsBundle\Entity\GalleryView'}

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name:  main
    user_class:     Application\Networking\InitCmsBundle\Entity\User
    group:
        group_class: Networking\InitCmsBundle\Entity\Group
    from_email:
            address:        webmaster@example.com
            sender_name:    net working Team

sonata_user:
    security_acl: true
    impersonating:
        route:                networking_init_cms_admin
        parameters:           { path: /}
    class:
        user: Application\Networking\InitCmsBundle\Entity\User
        group: Networking\InitCmsBundle\Entity\Group
    admin:                  # Admin Classes
        user:
            class:          Networking\InitCmsBundle\Admin\Entity\UserAdmin
            controller:     NetworkingInitCmsBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          Networking\InitCmsBundle\Admin\Entity\GroupAdmin
            controller:     NetworkingInitCmsBundle:CRUD
            translation:    SonataUserBundle

hwi_oauth:

    firewall_name: main

    connect:
        confirmation: true
        #account_connector: hwi_oauth.user.provider.fosub_bridge
        #registration_form_handler: hwi_oauth.registration.form.handler.fosub_bridge
        #registration_form: fos_user.registration.form

    resource_owners:
        facebook:
            type:                facebook
            client_id:           %socials.facebook.client_id%
            client_secret:       %socials.facebook.client_secret%
            scope:               "email user_birthday"

    fosub:
        username_iterations: 30
        properties:
            facebook: facebookUid

